version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume1/docker/matricula-webdownloader/docker/vpn-test/wireguard:/gluetun/wireguard
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_CONFIG_FILE=/gluetun/wireguard/wg0.conf
      - FIREWALL_INPUT_PORTS=5000
    ports:
      - "5055:5000"
    restart: unless-stopped

  matricula-downloader:
    image: ghcr.io/guenter-1953/matricula-webdownloader:sha-a5351c6 
    container_name: matricula-downloader
    network_mode: "service:gluetun"
    volumes:
      - /volume1/docker/matricula-webdownloader/data:/app/data
    restart: unless-stopped
