services:
  matricula:
    build: .
    container_name: matricula-downloader
    restart: unless-stopped
    ports:
      - "5055:5000"
    volumes:
      - /volume1/docker/matricula-webdownloader/data:/app/data
