version: "3"

services:
  matricula-downloader:
    image: ghcr.io/guenter-1953/matricula-webdownloader:latest
    container_name: matricula-downloader
    ports:
      - "5055:5000"
    volumes:
      - /volume1/docker/matricula-webdownloader/data:/app/data
    restart: unless-stopped
